### ISSUE TITLE
Make graphs with R

### ISSUE THREAD

**Issue by sstone93** [sstone93/comp3008p2#11]
Histogram 1:
- multicategory -- scheme
- x axis = num logins
- y axis = num users who had x logins

**Comment by sstone93** [comment]
Remember, histogram 1 is actually 3 histograms (one for total, one for successes, and one for failures

**Comment by TinekeVanderhorst** [comment]
Histogram 2:

- multicategory -- scheme

- x axis = login time

- y axis: num of users who had x login time

2 histograms, successful and unsuccessful

**Comment by TinekeVanderhorst** [comment]
Boxplot:

- Same axis' as histogram 2

- one box per scheme

Two boxplots, successful and unsuccessful

**Comment by sstone93** [comment]
documentation for multhist

**Comment by sstone93** [comment]
helps if I put the link...
https://www.rdocumentation.org/packages/plotrix/versions/3.6-4/topics/multhist

**Comment by TinekeVanderhorst** [comment]
Everything done. will figure out proper merging stuff on sunday.
