### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by ChantalForget** [sstone93/comp3008p2#6]
Use 16 choose 3 emojis

Options:
https://www.webpagefx.com/tools/emoji-cheat-sheet/

**Comment by ChantalForget** [comment]
my vote is :shipit: 💃 💨 🐙 💪 💩 ❤️ 😍 😁 😂 🎃 🚴 🐢 🌷 😡 👎 👍

**Comment by TinekeVanderhorst** [comment]
-Need to make sure emojis we use can be scaled up, we don't want users to be clicking tiny images or something really pixelated

**Comment by TinekeVanderhorst** [comment]
http://static.skaip.org/img/emoticons/180x180/f6fcff/turkey.gif

**Comment by sstone93** [comment]
We should use all emojis from one platform (i.e. skype) so that they all have a similar look

**Comment by ChantalForget** [comment]
http://emojione.com/developers/ might be useful

**Comment by sstone93** [comment]
👍
